/*
 * AddUser.java
 *
 * Created on April 9, 2009, 6:01 PM
 */
package librarymanagementbook;

import util.*;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.ButtonGroup;
import util.DBConnection;
import util.MD5;
import util.UseMethod;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class AddEmployee extends javax.swing.JFrame {

    JDateChooser date ;
    SimpleDateFormat dateFormat ;
    DBConnection d;
    Connection con;
    Statement stmt;
    static EmployManagement um;
    static  AddBorrow um1;

    /** Creates new form AddUser */
    /**
     * This constructor is used to initialize a new AddUser form object.
     * @param u -The UserManagement object
     */
    
//    public AddUser(AddBorrow u) {
//        um1 = u;
//        initComponents();
//        date = new JDateChooser(null, "dd-MM-yyyy");
//        dateFormat = new SimpleDateFormat("MM-dd-yyyy");
//        pn_date.add(date);
//        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
//        d = new DBConnection();
//        con = d.connect();
////        try {
////           // stmt = con.createStatement();
////        } catch (SQLException ex) {
////            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
////        }
//        ButtonGroup bg = new ButtonGroup();
//        bg.add(rb_male);
//        bg.add(rb_female);
//
//
//    }
    public AddEmployee(EmployManagement u) {
        um = u;
        initComponents();
        date = new JDateChooser(null, "dd-MM-yyyy");
        dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        pn_date.add(date);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
        d = new DBConnection();
        con = d.connect();
//        try {
//           // stmt = con.createStatement();
//        } catch (SQLException ex) {
//            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
//        }
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_male);
        bg.add(rb_female);


    }
    
    
    public AddEmployee(AddBorrow u1) {
        this.um1 = u1;
        initComponents();
        date = new JDateChooser(null, "dd-MM-yyyy");
        dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        pn_date.add(date);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
        d = new DBConnection();
        con = d.connect();
//        try {
//           // stmt = con.createStatement();
//        } catch (SQLException ex) {
//            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
//        }
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_male);
        bg.add(rb_female);


    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        lb_repass = new javax.swing.JLabel();
        lb_Address = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        lb_birthday = new javax.swing.JLabel();
        pn_date = new javax.swing.JPanel();
        lb_gender = new javax.swing.JLabel();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        lb_phone = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        txt_Adress = new javax.swing.JTextField();
        txt_Department = new javax.swing.JTextField();
        bt_cancel = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Information"));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        lb_repass.setText("Department");

        lb_Address.setText("Address");

        lb_username.setText("Employee Name");

        lb_email.setText("Email");

        lb_birthday.setText("Birthday");

        pn_date.setLayout(new java.awt.GridLayout(1, 0));

        lb_gender.setText("Gender");

        rb_male.setText("Male");

        rb_female.setSelected(true);
        rb_female.setText("Female");
        rb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femaleActionPerformed(evt);
            }
        });

        lb_phone.setText("Phone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_repass)
                    .addComponent(lb_Address)
                    .addComponent(lb_username)
                    .addComponent(lb_birthday)
                    .addComponent(lb_gender)
                    .addComponent(lb_phone)
                    .addComponent(lb_email))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Department)
                    .addComponent(txt_Adress)
                    .addComponent(txt_email)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_male)
                        .addGap(18, 18, 18)
                        .addComponent(rb_female))
                    .addComponent(pn_date, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txt_phone))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_username)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Address)
                    .addComponent(txt_Adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_repass)
                    .addComponent(txt_Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lb_email))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_birthday)
                    .addComponent(pn_date, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gender)
                    .addComponent(rb_male)
                    .addComponent(rb_female))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_phone)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        bt_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        bt_add.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\LibraryManagementSystem\\src\\images\\edit_add.png")); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_add)
                        .addGap(60, 60, 60)
                        .addComponent(bt_cancel)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancel)
                    .addComponent(bt_add))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_usernameActionPerformed

private void rb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femaleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_rb_femaleActionPerformed

private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed

    String Username = txt_username.getText();
    String Email = txt_email.getText();
    String Depa = txt_Department.getText();
    String birthdate ;
        try {
            birthdate = dateFormat.format(date.getDate());
        } catch (NullPointerException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Please select birthday!");
            date.requestFocus();
            return;
        }
    
    if(!Email.equals(""))
    {
        if(UseMethod.checkEmail(Email) == false)
        {
            JOptionPane.showMessageDialog(null, "You entered invalid email address format!");
            
            return;
        }
    }
   
    if (Username.equals("")) {
        JOptionPane.showMessageDialog(null, "Employee name not empty!");
        txt_username.requestFocus();
        txt_username.selectAll();
        return;
    }
    if(Email.equals(""))
    {
            JOptionPane.showMessageDialog(null, "Email not empty!");
            txt_email.requestFocus();
            txt_email.selectAll();
            return;
        
    }
    if(Depa.equals("")){
    
        JOptionPane.showMessageDialog(this, "Department not empty");
        return;
    }

//    String sqlCheckUser = "select UserName from tblUsers where UserName = '" + Username + "'";
//    ResultSet rsCheck;
//    try {
//        stmt = con.createStatement();
//        rsCheck = stmt.executeQuery(sqlCheckUser);
//        if (rsCheck.next()) {
//            JOptionPane.showMessageDialog(null, "Username is exists!");
//            txt_username.requestFocus();
//            txt_username.selectAll();
//            return;
//        }
//        d.disconnect(rsCheck);
//        d.disconnect(stmt);
//        d.disconnect(con);
//    } catch (SQLException ex) {
//        Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
//    }

    String Addres = txt_Adress.getText();

    if(Addres.equals(""))
    {
            JOptionPane.showMessageDialog(null, "Address not empty!");
            txt_Adress.requestFocus();
            txt_Adress.selectAll();
            return;
    }
    
        int phone = 0;
        if (txt_phone.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this,"Phone not empty");
            return;
        } else {
            try {
                phone = Integer.parseInt(txt_phone.getText());
            } catch (NumberFormatException ne) {
                ne.printStackTrace();
                JOptionPane.showMessageDialog(null, "Phone not a number!");
                txt_phone.requestFocus();
                txt_phone.selectAll();
                return;
            }
        }
        boolean gender = false;
        if (rb_female.isSelected()) {
            gender = false;
        }
        if (rb_male.isSelected()) {
            gender = true;
        }
        String sqlEmployee = "insert into Employee(e_Name,Address,PhoneNumber,Department,Birthday,Email,Gender) values('" + Username + "','" + Addres + "','" + phone + "','" + Depa + "','" + birthdate + "','" + Email +"','"+gender+"')";
        d.execute(sqlEmployee);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Add new Employee successful!");
        if(um != null){
        um.SetModel();
        }
        if(um1 != null){
        
            um1.txt_CustName.setText(Username);
        }
     

}//GEN-LAST:event_bt_addActionPerformed

private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
    this.dispose();
}//GEN-LAST:event_bt_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddEmployee(um).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_Address;
    private javax.swing.JLabel lb_birthday;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_gender;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_repass;
    private javax.swing.JLabel lb_username;
    private javax.swing.JPanel pn_date;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextField txt_Adress;
    private javax.swing.JTextField txt_Department;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
