/*
 * UserManagement.java
 *
 * Created on April 6, 2009, 9:38 PM
 */
package librarymanagementbook;

import java.awt.event.ItemEvent;
import java.sql.*;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.CloseableTabComponent;
import util.DBConnection;
import util.Search;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class BookManagement extends javax.swing.JPanel {

    DBConnection dc;
    Connection con;
    Statement stmt1, stmt2;
    ResultSet rs;
    Vector vtcolumn_book, vtdata_book;
    DefaultTableModel boook_model = new DefaultTableModel(vtdata_book, vtcolumn_book);
    SimpleDateFormat formatDate;

    /** Creates new form UserManagement */
    public BookManagement() {
        initComponents();

        formatDate = new SimpleDateFormat("dd-MM-yyyy");
        dc = new DBConnection();
        //dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        SetModel();
    }

    /**This method use to set data model for table
     * 
     */
    public void SetModel() {
        try {
            con = dc.connect();
            tb_Book.setModel(boook_model);
            stmt2 = con.createStatement();
            vtdata_book = new Vector();
            vtcolumn_book = new Vector();

            //Add Header for User Table Model
            vtcolumn_book.add("ID");
            vtcolumn_book.add("CallNumber");
            vtcolumn_book.add("ISBN");
            vtcolumn_book.add("Title");
            vtcolumn_book.add("NumOfCopy");
            vtcolumn_book.add("NameAuthor");
            vtcolumn_book.add("PublishingHouse ");
            vtcolumn_book.add("NumOfContinue ");
            vtcolumn_book.add("Status ");
            String sqlUser = "select BookID,CallNumber,Isbn,Title,NumOfCopies,NameAuthor,PublishHouse,bookContinue from Book";
            ResultSet rsUser = stmt2.executeQuery(sqlUser);



            while (rsUser.next()) {

                Vector temp = new Vector();
                temp.add(rsUser.getString(1));
                temp.add(rsUser.getString(2));
                temp.add(rsUser.getString(3));
                temp.add(rsUser.getString(4));
                temp.add(rsUser.getInt(5));
                temp.add(rsUser.getString(6));
                temp.add(rsUser.getString(7));
                int q1 =rsUser.getInt(8); 
                temp.add(q1);
                if(q1 <= 0){
                temp.add("End Book");
                }else{
                temp.add("Continue Book");
                }
                
                vtdata_book.add(temp);
            }


            boook_model = new DefaultTableModel(vtdata_book, vtcolumn_book) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tb_Book.setModel(boook_model);

            dc.disconnect(rsUser);
            dc.disconnect(stmt2);
            dc.disconnect(con);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**This method use to edit user
     * 
     */
    public void DoEdit() {
         int Row[] = tb_Book.getSelectedRows();
        if (Row.length > 1) {
            JOptionPane.showMessageDialog(null, "You can choose only one Book at same time!");
            return;
        }
        if (tb_Book.getSelectedRow() >= 0) {
            EditBook eu = new EditBook(this);
            eu.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "You have not choose any Book to edit");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Book = new javax.swing.JTable();
        bt_edit = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        lb_userType1 = new javax.swing.JLabel();
        txt_SearchKey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_SearchTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_SearchISBN = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List All Books"));

        tb_Book.setAutoCreateRowSorter(true);
        tb_Book.setModel(boook_model);
        tb_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_BookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Book);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil_48.png"))); // NOI18N
        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete.png"))); // NOI18N
        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add user.png"))); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        lb_userType1.setText("CallNumber");

        txt_SearchKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SearchKeyKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Title");

        jLabel2.setText("ISBN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_userType1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SearchISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_SearchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(122, 122, 122)
                        .addComponent(bt_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_delete)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_add)
                        .addComponent(bt_edit)
                        .addComponent(bt_delete)
                        .addComponent(lb_userType1)
                        .addComponent(txt_SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txt_SearchISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txt_SearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
//
    DoEdit();
}//GEN-LAST:event_bt_editActionPerformed

private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed

     int Row[] = tb_Book.getSelectedRows();
    if (Row.length > 1) {
        JOptionPane.showMessageDialog(null, "You can choose only one Book at same time!");
        return;
    }
    if (tb_Book.getSelectedRow() < 0) {
        JOptionPane.showMessageDialog(null, "Please choose Book to delete!");
    } else {



            Vector v = new Vector();
           // v = (Vector) d.getDataVector().elementAt(RowIndex[i]);
            v = (Vector) boook_model.getDataVector().elementAt(tb_Book.getSelectedRow());
            String sqlCheck = "select bookID from Borrowdetail where BookID = " + v.elementAt(0);
            dc.executequery(sqlCheck);
            if (dc.data.size() > 0) {
                JOptionPane.showMessageDialog(null, "Book : " + v.elementAt(3) + " had Borrow you can\' delete!");
                return;
            }
            String sql = "delete from Book where BookID = " + v.elementAt(0) + "";
            if (JOptionPane.showConfirmDialog(null, "Are you sure want to delete Book " + v.elementAt(3), "Library Management System", JOptionPane.OK_CANCEL_OPTION) == 0) {
                try {
                   con = dc.connect();
                   Statement st = con.createStatement();
                    int j = st.executeUpdate(sql);
                    if (j < 0) {

                        JOptionPane.showMessageDialog(null, "Delete Book " + v.elementAt(3) + " unsuccessful!");
                    }
                    if (j > 0) {
                        JOptionPane.showMessageDialog(null, "Delete Book " + v.elementAt(3) + " succesfull!");
                    }
                    st.close();
                    dc.disconnect(con);
                } catch (SQLException ex) {
                    Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        
        SetModel();
    }
    
}//GEN-LAST:event_bt_deleteActionPerformed

private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
    AddBook obj = new AddBook(this);  
    obj.setVisible(true);
}//GEN-LAST:event_bt_addActionPerformed
    /**This method use to seach user
     * 
     */
    public void search() {
         if (txt_SearchKey.getText().equals("")) {
              if (txt_SearchISBN.getText().equals("") && txt_SearchTitle.getText().equals("")) {
                String sql = "select bookID,CallNumber,Isbn,Title,NumOfCopies,NameAuthor,PublishHouse,bookContinue from Book";
                ReturnSalesSearch(sql);
                return;
            }else if (txt_SearchISBN.getText().equals("")) {
                //String sql = "select CallNumber,Isbn,Title,NumOfCopies,NameAuthor,PublishHouse,bookContinue from Book";
                 String sql = "exec tblBook_SearchByTitle '" + txt_SearchTitle.getText() + "'";
                ReturnSalesSearch(sql);
                return;
            } else if (txt_SearchTitle.getText().equals("")) {
                String sql = "exec tblBook_SearchByISBN '" + txt_SearchISBN.getText() + "'";
                ReturnSalesSearch(sql);
            } else {
                String sql = "exec tblBook_SearchByTitleISBN '" + txt_SearchTitle.getText() +"','" + txt_SearchISBN.getText() + "'";
                ReturnSalesSearch(sql);
            }

        } else {
            if (txt_SearchISBN.getText().equals("") && txt_SearchTitle.getText().equals("")) {
                String searchKey = txt_SearchKey.getText();
                String sql = "exec tblBook_SearchByCallnumber '" + searchKey + "'";
                ReturnSalesSearch(sql);
                return;
            }else
            if (txt_SearchTitle.getText().equals("")) {
                String searchKey = txt_SearchKey.getText();
                String sql = "exec tblBook_SearchByCallnumberAndISBN '" + searchKey + "','" + txt_SearchISBN.getText() + "'";
                ReturnSalesSearch(sql);
            }else
             if (txt_SearchISBN.getText().equals("")) {
                String searchKey = txt_SearchKey.getText();
                String sql = "exec tblBook_SearchByCallNumberAndtitle '" + searchKey + "','" + txt_SearchTitle.getText() + "'";
                ReturnSalesSearch(sql);
            }else

            if ((!txt_SearchKey.getText().equals("")) && (txt_SearchISBN.getText().equals(""))&&(txt_SearchTitle.getText().equals(""))) {
                String searchKey = txt_SearchKey.getText();
                String sql = "exec tblBook_SearchByCallAndtitleAndIS '" + searchKey + "','" + txt_SearchISBN + "','" + txt_SearchTitle + "'";
                ReturnSalesSearch(sql);
            }

        }
    }
    
     public void ReturnSalesSearch(String sql) {
         vtdata_book = new Vector();
         con = dc.connect();
        try {
           Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                Vector temp = new Vector();
                
                temp.add(rs.getString(1));
                temp.add(rs.getString(2));
                temp.add(rs.getString(3));
                temp.add(rs.getString(4));
                temp.add(rs.getInt(5));
                temp.add(rs.getString(6));
                temp.add(rs.getString(7));
                int q1 =rs.getInt(8); 
                temp.add(q1);
                if(q1 <= 0){
                temp.add("End Book");
                }else{
                temp.add("Continue Book");
                }
                
                vtdata_book.add(temp);
            }

          
             boook_model = new DefaultTableModel(vtdata_book, vtcolumn_book) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tb_Book.setModel(boook_model);
              if(vtdata_book.size() == 0){
            
                JOptionPane.showMessageDialog(this, "Not search book!!!");
                
            }
            dc.disconnect(rs);
            dc.disconnect(stmt);
            dc.disconnect(con);


        } catch (SQLException ex) {
            Logger.getLogger(BorrowManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    search();
}//GEN-LAST:event_jButton1ActionPerformed

private void txt_SearchKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyKeyTyped
//    if (evt.getKeyChar() == evt.VK_ENTER) {
//        Search();
//    }
}//GEN-LAST:event_txt_SearchKeyKeyTyped

private void tb_BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_BookMouseClicked
//    if (evt.getClickCount() == 2) {
//        DoEdit();
//    }
}//GEN-LAST:event_tb_BookMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_userType1;
    public javax.swing.JTable tb_Book;
    private javax.swing.JTextField txt_SearchISBN;
    private javax.swing.JTextField txt_SearchKey;
    private javax.swing.JTextField txt_SearchTitle;
    // End of variables declaration//GEN-END:variables
}
