/*
 * EditUser.java
 *
 * Created on April 9, 2009, 6:02 PM
 */
package librarymanagementbook;

import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import util.DBConnection;
import util.UseMethod;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class EditUser extends javax.swing.JFrame {

    DBConnection d;
    static Vector vtUser;
    int userID;
    String Username;
    JDateChooser date;
    SimpleDateFormat dateFormat;
    static UserManagement um;

    /** Creates new form EditUser */
    /**
     * This constructor is used to initialize a new EditUser form object.
     * @param u - The UserManagement object
     */
    public EditUser(UserManagement u) {
        um = u;
        initComponents();
        d = new DBConnection();
        dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_female1);
        bg.add(rb_male1);
        vtUser = (Vector) um.user_model.getDataVector().elementAt(um.tb_User.getSelectedRow());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date d = null;
        java.sql.Date sqlD = null;
        try {
            d = formatter.parse(vtUser.elementAt(3).toString());
            sqlD = new java.sql.Date(d.getTime());

        } catch (ParseException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        date = new JDateChooser(sqlD, "dd-MM-yyyy");
        pn_date.add(date);
        if (vtUser.elementAt(4) == null) {
            rb_male1.setSelected(true);
        }
        if (vtUser.elementAt(4).toString().equals("Male")) {
            rb_male1.setSelected(true);
        }
        if (vtUser.elementAt(4).toString().equals("Female")) {
            rb_female1.setSelected(true);
        }
        if (vtUser.elementAt(5) == null) {
            txt_phone1.setText("");
        } else {
            txt_phone1.setText(vtUser.elementAt(5).toString());
        }

        txt_username1.setText(vtUser.elementAt(0).toString());
        if (vtUser.elementAt(1) == null) {
            txt_fullname1.setText("");
        } else {
            txt_fullname1.setText(vtUser.elementAt(1).toString());
        }

        if (vtUser.elementAt(2) == null) {
            txt_email1.setText("");
        } else {
            txt_email1.setText(vtUser.elementAt(2).toString());
        }

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);

        Username = txt_username1.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_apply = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_username1 = new javax.swing.JTextField();
        lb_username1 = new javax.swing.JLabel();
        lb_fullname = new javax.swing.JLabel();
        txt_fullname1 = new javax.swing.JTextField();
        txt_email1 = new javax.swing.JTextField();
        lb_email1 = new javax.swing.JLabel();
        bt_ResetPass = new javax.swing.JButton();
        lb_gender1 = new javax.swing.JLabel();
        rb_male1 = new javax.swing.JRadioButton();
        rb_female1 = new javax.swing.JRadioButton();
        txt_phone1 = new javax.swing.JTextField();
        lb_phone1 = new javax.swing.JLabel();
        pn_date = new javax.swing.JPanel();
        lb_birthday1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit User");
        setResizable(false);

        bt_apply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_ok.png"))); // NOI18N
        bt_apply.setText("Apply");
        bt_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_applyActionPerformed(evt);
            }
        });

        bt_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Information"));

        txt_username1.setEditable(false);
        txt_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username1ActionPerformed(evt);
            }
        });

        lb_username1.setText("UserName");

        lb_fullname.setText("Full Name");

        lb_email1.setText("Email");

        bt_ResetPass.setText("Reset Password");
        bt_ResetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ResetPassActionPerformed(evt);
            }
        });

        lb_gender1.setText("Gender");

        rb_male1.setText("Male");

        rb_female1.setText("Female");
        rb_female1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_female1ActionPerformed(evt);
            }
        });

        lb_phone1.setText("Phone");

        pn_date.setLayout(new java.awt.GridLayout(1, 0));

        lb_birthday1.setText("Birthday");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_username1)
                    .addComponent(lb_fullname)
                    .addComponent(lb_email1)
                    .addComponent(lb_birthday1)
                    .addComponent(lb_phone1)
                    .addComponent(lb_gender1))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pn_date, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(225, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_male1)
                        .addGap(10, 10, 10)
                        .addComponent(rb_female1)
                        .addContainerGap(248, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_phone1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txt_email1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txt_fullname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txt_username1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_ResetPass)
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_username1)
                    .addComponent(txt_username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ResetPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_fullname)
                    .addComponent(txt_fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_male1)
                        .addComponent(rb_female1))
                    .addComponent(lb_gender1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_phone1)
                    .addComponent(txt_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_birthday1)
                    .addComponent(pn_date, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(bt_apply)
                        .addGap(68, 68, 68)
                        .addComponent(bt_cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_apply)
                    .addComponent(bt_cancel))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txt_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_username1ActionPerformed

private void rb_female1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_female1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_rb_female1ActionPerformed

private void bt_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_applyActionPerformed

    String FullName = txt_fullname1.getText();
    String Email = txt_email1.getText();
    if (Email.equals("")) {
        JOptionPane.showMessageDialog(null, " email not empty!");
        return;
    }
    if (!Email.equals("")) {
        if (UseMethod.checkEmail(Email) == false) {
            JOptionPane.showMessageDialog(null, "You entered invalid email address format!");

            return;
        }
    }
    if (FullName.equals("")) {
        JOptionPane.showMessageDialog(null, "FullName not empty!");
        return;
    }
    String birthdate = null;
    boolean gender = false;
    try {
        birthdate = dateFormat.format(date.getDate());
    } catch (NullPointerException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Please select birthday!");
        return;
    }


    if (txt_phone1.getText().toString().equals("")) {
        JOptionPane.showMessageDialog(null, " Phone not empty!");
        return;
    }

    int phone = 0;
    try {
        phone = Integer.parseInt(txt_phone1.getText());
    } catch (NumberFormatException ne) {
        ne.printStackTrace();
        JOptionPane.showMessageDialog(null, "Phone not a number!");
        txt_phone1.requestFocus();
        txt_phone1.selectAll();
        return;
    }

    if (rb_female1.isSelected()) {
        gender = false;
    }
    if (rb_male1.isSelected()) {
        gender = true;
    }
    String sqlUserUpdate = "update tblUsers set U_Name = '" + FullName + "',Email = '" + Email + "',BirthDate = '" + birthdate + "',Gender = '" + gender + "' ,Phone = '" + phone + "' where Username = '" + Username + "'";
    d.execute(sqlUserUpdate);



    JOptionPane.showMessageDialog(null, "Edit User Success!");
    this.dispose();
    um.SetModel();
}//GEN-LAST:event_bt_applyActionPerformed

private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
    this.dispose();
}//GEN-LAST:event_bt_cancelActionPerformed

private void bt_ResetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ResetPassActionPerformed

    String updatePassforUser = "update tblUsers set Password = 'fcea920f7412b5da7be0cf42b8c93759' where Username = '" + Username + "'";

    if (JOptionPane.showConfirmDialog(null, "Are you sure want to reset password for : '" + Username + "'", "Medical StoreBilling", JOptionPane.OK_CANCEL_OPTION) == 0) {

        d.execute(updatePassforUser);
        JOptionPane.showMessageDialog(null, "Reset password for : '" + Username + "' success,Password now is '1234567'");
        this.dispose();
    }
}//GEN-LAST:event_bt_ResetPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditUser(um).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ResetPass;
    private javax.swing.JButton bt_apply;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_birthday1;
    private javax.swing.JLabel lb_email1;
    private javax.swing.JLabel lb_fullname;
    private javax.swing.JLabel lb_gender1;
    private javax.swing.JLabel lb_phone1;
    private javax.swing.JLabel lb_username1;
    private javax.swing.JPanel pn_date;
    private javax.swing.JRadioButton rb_female1;
    private javax.swing.JRadioButton rb_male1;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextField txt_fullname1;
    private javax.swing.JTextField txt_phone1;
    private javax.swing.JTextField txt_username1;
    // End of variables declaration//GEN-END:variables
}
