/*
 * AddUser.java
 *
 * Created on April 9, 2009, 6:01 PM
 */
package librarymanagementbook;

import librarymanagementbook.*;
import util.*;
import librarymanagementbook.*;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.ButtonGroup;
import util.DBConnection;
import util.MD5;
import util.UseMethod;
import java.util.*;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class EditBook extends javax.swing.JFrame {
    CallNumberEdit cm = new CallNumberEdit();
    DBCallISBN dbt = new DBCallISBN();
    static Vector vtUser;
    DBConnection d;
    Connection con;
    Statement stmt;
    static BookManagement um;

    public EditBook(BookManagement u) {
        um = u;
        initComponents();
       
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
        d = new DBConnection();
        con = d.connect();
        vtUser = (Vector) um.boook_model.getDataVector().elementAt(um.tb_Book.getSelectedRow());
        

        
        if (vtUser.elementAt(0) == null) {
            jTextField3.setText("");
        } else {
            jTextField3.setText(vtUser.elementAt(0).toString());
        }
        if (vtUser.elementAt(3) == null) {
            titleTextField.setText("");
        } else {
            titleTextField.setText(vtUser.elementAt(3).toString());
        }

         if (vtUser.elementAt(5) == null) {
            authorTextField.setText("");
        } else {
            authorTextField.setText(vtUser.elementAt(5).toString());
        }
         if (vtUser.elementAt(1) == null) {
            callnumberTextField.setText("");
        } else {
            callnumberTextField.setText(vtUser.elementAt(1).toString());
        }
         if (vtUser.elementAt(2) == null) {
            isbnTextField.setText("");
        } else {
            isbnTextField.setText(vtUser.elementAt(2).toString());
        }
         if (vtUser.elementAt(4) == null) {
            jTextField1.setText("");
        } else {
            jTextField1.setText(vtUser.elementAt(4).toString());
        }
         if (vtUser.elementAt(7) == null) {
            jTextField2.setText("");
        } else {
            jTextField2.setText(vtUser.elementAt(7).toString());
        }
         if (vtUser.elementAt(6) == null) {
            txt_phone.setText("");
        } else {
            txt_phone.setText(vtUser.elementAt(6).toString());
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        titleTextField = new javax.swing.JTextField();
        lb_repass = new javax.swing.JLabel();
        lb_pass = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        lb_fullname = new javax.swing.JLabel();
        isbnTextField = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        lb_birthday = new javax.swing.JLabel();
        lb_gender = new javax.swing.JLabel();
        lb_phone = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        authorTextField = new javax.swing.JTextField();
        callnumberTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_cancel = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Book");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Information"));

        titleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextFieldActionPerformed(evt);
            }
        });

        lb_repass.setText("CallNumber");

        lb_pass.setText("NameAuthor");

        lb_username.setText("Title");

        lb_fullname.setText("Subject");

        isbnTextField.setEnabled(false);

        lb_email.setText("ISBN ");

        lb_birthday.setText("NumOfCopy");

        lb_gender.setText("NumOfContinue");

        lb_phone.setText("Publish House");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(dbt.getSubject()));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        callnumberTextField.setEnabled(false);
        callnumberTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callnumberTextFieldMouseClicked(evt);
            }
        });
        callnumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callnumberTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("BookID");

        jTextField3.setEditable(false);

        titleLabel.setForeground(new java.awt.Color(255, 0, 0));
        titleLabel.setText("* Invalid Title");
        titleLabel.setVisible(false);

        authorLabel.setForeground(new java.awt.Color(255, 0, 0));
        authorLabel.setText("* Invalid Author");
        authorLabel.setVisible(false);

        jLabel2.setText("Please Mouse Click ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_phone)
                    .addComponent(lb_gender)
                    .addComponent(lb_fullname)
                    .addComponent(lb_birthday)
                    .addComponent(lb_email)
                    .addComponent(lb_pass)
                    .addComponent(lb_repass)
                    .addComponent(jLabel1)
                    .addComponent(lb_username))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(titleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(authorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(callnumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(authorLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_username)
                    .addComponent(titleLabel))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_pass)
                    .addComponent(authorLabel))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(callnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(lb_repass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_fullname)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_birthday))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_phone)))
        );

        bt_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        bt_add.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\LibraryManagementSystem\\src\\images\\edit_add.png")); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_add)
                        .addGap(46, 46, 46)
                        .addComponent(bt_cancel)
                        .addGap(184, 184, 184))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_titleTextFieldActionPerformed

private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed

    int phone;
    int phon;
    String title = titleTextField.getText();
    String author = authorTextField.getText();
    String callNu = callnumberTextField.getText();
    //int a = jComboBox1.getSelectedIndex();
    String isb = isbnTextField.getText();
    String NumCopy = jTextField1.getText();
    String NumContinu = jTextField2.getText();
    String publishHous = txt_phone.getText();
    int Bookid = Integer.parseInt(jTextField3.getText());
    
    
 
//   
//    if (title.equals("")) {
//        JOptionPane.showMessageDialog(null, "Title not empty!");
//        titleTextField.requestFocus();
//        titleTextField.selectAll();
//        return;
//    }
//    if(author.equals(""))
//    {
//            JOptionPane.showMessageDialog(null, "Author not empty!");
//            authorTextField.requestFocus();
//            authorTextField.selectAll();
//            return;
//    }
    
     if(!ValidateInput.validateTitle(titleTextField.getText()))
     {
            titleLabel.setVisible(true);
            return;
     }else titleLabel.setVisible(false);
        if(!ValidateInput.validateAuthor(authorTextField.getText())){
            authorLabel.setVisible(true);
            return;
        }
        else authorLabel.setVisible(false);
    
  if(callNu.equals(""))
    {
            JOptionPane.showMessageDialog(null, "CallNumber not empty!");
            authorTextField.requestFocus();
            authorTextField.selectAll();
            return;
    }
    
    
//    if(a == 0){
//            JOptionPane.showMessageDialog(null, " You must select!!!");
//            return;
//    }
     if(isb.equals(""))
    {
            JOptionPane.showMessageDialog(null, "ISBN not empty!");
            isbnTextField.requestFocus();
            isbnTextField.selectAll();
            return;
    }
    
     if(NumCopy.equals(""))
    {
            JOptionPane.showMessageDialog(null, "NumOfCopy not empty!");
            jTextField1.requestFocus();
            jTextField1.selectAll();
            return;
    } else{
        
     try {
                phone = Integer.parseInt(NumCopy);
            } catch (NumberFormatException ne) {
                ne.printStackTrace();
                JOptionPane.showMessageDialog(null, "NumOfCopy not a number!");
                jTextField1.requestFocus();
                jTextField1.selectAll();
                return;
            }
    }
      if(NumContinu.equals(""))
    {
            JOptionPane.showMessageDialog(null, "NumOfContinue not empty!");
            jTextField2.requestFocus();
            jTextField2.selectAll();
            return;
    } else{
     try {
                phon = Integer.parseInt(NumContinu);
            } catch (NumberFormatException ne) {
                ne.printStackTrace();
                JOptionPane.showMessageDialog(null, "NumOfContinue not a number!");
                jTextField2.requestFocus();
                jTextField2.selectAll();
                return;
            }
        
    }
    
    if(Integer.parseInt(NumCopy) < Integer.parseInt(NumContinu)){
    
                JOptionPane.showMessageDialog(null, "NumOfCopy not small NumOfCotinue!!!");
                jTextField1.requestFocus();
                jTextField2.selectAll();
        
        
    }
//    if(phon != phone){
//         JOptionPane.showMessageDialog(null, "NumOfCopy not equal NumOfContinue!");
//         jTextField2.requestFocus();
//         jTextField2.selectAll();
//         return;
//    }

    if(publishHous.equals(""))
    {
            JOptionPane.showMessageDialog(null, "PublishHouse not empty!");
            txt_phone.requestFocus();
            txt_phone.selectAll();
            return;
    }
//  
//        int phone = 0;
//        if (txt_phone.getText().toString().equals("")) {
//            phone = 0;
//        } else {
//            try {
//                phone = Integer.parseInt(txt_phone.getText());
//            } catch (NumberFormatException ne) {
//                ne.printStackTrace();
//                JOptionPane.showMessageDialog(null, "Phone not a number!");
//                txt_phone.requestFocus();
//                txt_phone.selectAll();
//                return;
//            }
//        }
//        boolean gender = false;
       
       String sqlBookUpdate = "update Book set CallNumber = '" + callNu + "',ISBN = '" + isb + "',Title = '" + title + "',NameAuthor = '" + author + "' ,PublishHouse = '" + publishHous + "' ,NumofCopies = '" + NumCopy + "' ,BookContinue = '" + NumContinu + "' where BookID = '" + Bookid + "'";
       d.execute(sqlBookUpdate);
       JOptionPane.showMessageDialog(null, "Edit new Book successful!");
        this.dispose();
        um.SetModel();
     

}//GEN-LAST:event_bt_addActionPerformed

private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
    this.dispose();
}//GEN-LAST:event_bt_cancelActionPerformed

private void callnumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callnumberTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_callnumberTextFieldActionPerformed

private void callnumberTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callnumberTextFieldMouseClicked
// TODO add your handling code here:
      try {
            // TODO add your handling code here:
            callnumberTextField.setText(cm.getCallNumber(titleTextField.getText(), authorTextField.getText(),jTextField3.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_callnumberTextFieldMouseClicked

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
// TODO add your handling code here:
    String item = (String)jComboBox1.getSelectedItem();
        if(jComboBox1.getSelectedIndex()!=0)
        isbnTextField.setText(dbt.getisbnEdit(dbt.getsubjectid(item),jTextField3.getText()));
        else
            isbnTextField.setText(null);

}//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditBook(um).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JTextField callnumberTextField;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lb_birthday;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_fullname;
    private javax.swing.JLabel lb_gender;
    private javax.swing.JLabel lb_pass;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_repass;
    private javax.swing.JLabel lb_username;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
