/*
 * UserManagement.java
 *
 * Created on April 6, 2009, 9:38 PM
 */
package librarymanagementbook;

import util.*;
import librarymanagementbook.*;
import java.awt.event.ItemEvent;
import java.sql.*;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.CloseableTabComponent;
import util.DBConnection;
import util.Search;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class EmployManagement extends javax.swing.JPanel {

    DBConnection dc;
    Connection con;
    Statement stmt1, stmt2;
    ResultSet rs;
    Vector vtcolumn_employee, vtdata_employee;
    DefaultTableModel employee_model = new DefaultTableModel(vtdata_employee, vtcolumn_employee);
    SimpleDateFormat formatDate;

    /** Creates new form UserManagement */
    public EmployManagement() {
        initComponents();
        formatDate = new SimpleDateFormat("dd-MM-yyyy");
        dc = new DBConnection();
        //dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        SetModel();
    }

    /**This method use to set data model for table
     * 
     */
    public void SetModel() {
        try {
            con = dc.connect();
            tb_Employee.setModel(employee_model);
            stmt2 = con.createStatement();
            vtdata_employee = new Vector();
            vtcolumn_employee = new Vector();

            //Add Header for User Table Model
            vtcolumn_employee.add("ID");
            vtcolumn_employee.add("EmployeeName");
            vtcolumn_employee.add("Address");
            vtcolumn_employee.add("Phone");
            vtcolumn_employee.add("Department");
            vtcolumn_employee.add("Birthday");
            vtcolumn_employee.add("Email");
            vtcolumn_employee.add("Gender");

            String sqlUser = "select EmployeeID,e_Name,Address,PhoneNumber,Department,Birthday,Email,Gender from Employee";
            ResultSet rsUser = stmt2.executeQuery(sqlUser);



            while (rsUser.next()) {

                Vector temp = new Vector();
                temp.add(rsUser.getInt(1));
                temp.add(rsUser.getString(2));
                temp.add(rsUser.getString(3));
                temp.add(rsUser.getString(4));
                temp.add(rsUser.getString(5));
                temp.add(formatDate.format(rsUser.getDate(6)));
                temp.add(rsUser.getString(7));
                boolean gender = rsUser.getBoolean(8);
//                temp.add(rsUser.getString(1));
//                temp.add(rsUser.getString(2));
//                temp.add(rsUser.getString(3));
//                temp.add(rsUser.getString(4));
//                temp.add(formatDate.format(rsUser.getDate(5)));
//                temp.add(rsUser.getString(6));
//                boolean gender = rsUser.getBoolean(7);


                if (gender == true) {
                    temp.add("Male");
                }

                if (gender == false) {
                    temp.add("Female");
                }

                vtdata_employee.add(temp);
            }
            employee_model = new DefaultTableModel(vtdata_employee, vtcolumn_employee) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tb_Employee.setModel(employee_model);

            dc.disconnect(rsUser);
            dc.disconnect(stmt2);
            dc.disconnect(con);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**This method use to edit user
     * 
     */
    public void DoEdit() {
        int Row[] = tb_Employee.getSelectedRows();
        if (Row.length > 1) {
            JOptionPane.showMessageDialog(null, "You can choose only one Employee at same time!");
            return;
        }

        if (tb_Employee.getSelectedRow() >= 0) {
            EditEmployee eu = new EditEmployee(this);
            eu.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "You have not choose any Employee to edit");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Employee = new javax.swing.JTable();
        bt_edit = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        lb_userType1 = new javax.swing.JLabel();
        txt_SearchKey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List All Employee"));

        tb_Employee.setAutoCreateRowSorter(true);
        tb_Employee.setModel(employee_model);
        tb_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_EmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Employee);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil_48.png"))); // NOI18N
        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete.png"))); // NOI18N
        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add user.png"))); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        lb_userType1.setText("EmployeeName");

        txt_SearchKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SearchKeyKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lb_userType1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                        .addComponent(bt_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_delete)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_add)
                        .addComponent(bt_edit)
                        .addComponent(bt_delete)
                        .addComponent(lb_userType1)
                        .addComponent(txt_SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
//
    DoEdit();
}//GEN-LAST:event_bt_editActionPerformed

private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed

    int Row[] = tb_Employee.getSelectedRows();
    if (Row.length > 1) {
        JOptionPane.showMessageDialog(null, "You can choose only one Employee at same time!");
        return;
    }
    if (tb_Employee.getSelectedRow() < 0) {
        JOptionPane.showMessageDialog(null, "Please choose Employee to delete!");
    } else {


//        Vector v = new Vector();
//        String UserName = null;
//        v = (Vector) employee_model.getDataVector().elementAt(tb_Employee.getSelectedRow());
//        UserName = v.elementAt(0).toString();
//       int[] RowIndex = tb_customer.getSelectedRows();
//        for (int i = 0; i < RowIndex.length; i++) {
            Vector v = new Vector();
           // v = (Vector) d.getDataVector().elementAt(RowIndex[i]);
            v = (Vector) employee_model.getDataVector().elementAt(tb_Employee.getSelectedRow());
            String sqlCheck = "select EmployeeID from Borrow where EmployeeID = " + v.elementAt(0);
            dc.executequery(sqlCheck);
            if (dc.data.size() > 0) {
                JOptionPane.showMessageDialog(null, "Employee : " + v.elementAt(1) + " had Borrow you can\' delete!");
                return;
            }
            String sql = "delete from Employee where EmployeeID = " + v.elementAt(0) + "";
            if (JOptionPane.showConfirmDialog(null, "Are you sure want to delete employee " + v.elementAt(1), "Library Management System", JOptionPane.OK_CANCEL_OPTION) == 0) {
                try {
                   con = dc.connect();
                   Statement st = con.createStatement();
                    int j = st.executeUpdate(sql);
                    if (j < 0) {

                        JOptionPane.showMessageDialog(null, "Delete employee " + v.elementAt(1) + " unsuccessful!");
                    }
                    if (j > 0) {
                        JOptionPane.showMessageDialog(null, "Delete employee " + v.elementAt(1) + " succesfull!");
                    }
                    st.close();
                    dc.disconnect(con);
                } catch (SQLException ex) {
                    Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        
        SetModel();
    }
}//GEN-LAST:event_bt_deleteActionPerformed

private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
    AddEmployee au = new AddEmployee(this);
    au.setVisible(true);
}//GEN-LAST:event_bt_addActionPerformed
    /**This method use to seach user
     * 
     */
    public void search() {
        try {
            String searchKey = txt_SearchKey.getText();
            Search s = new Search();
            con = dc.connect();
            stmt1 = con.createStatement();


            String sql = s.getSQLQuery("Employee", searchKey);

            vtdata_employee = new Vector();
            ResultSet rsUser = stmt1.executeQuery(sql);
            while (rsUser.next()) {

                Vector temp = new Vector();

                temp.add(rsUser.getString(1));
                temp.add(rsUser.getString(2));
                temp.add(rsUser.getString(3));
                temp.add(rsUser.getString(4));
                temp.add(rsUser.getString(5));
                temp.add(formatDate.format(rsUser.getDate(6)));
                temp.add(rsUser.getString(7));
                boolean gender = rsUser.getBoolean(8);


                if (gender == true) {
                    temp.add("Male");
                }

                if (gender == false) {
                    temp.add("Female");
                }

                vtdata_employee.add(temp);
            }

            employee_model = new DefaultTableModel(vtdata_employee, vtcolumn_employee) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tb_Employee.setModel(employee_model);
            if (vtdata_employee.size() == 0) {

                JOptionPane.showMessageDialog(this, "No Search Employee! ");
            }
            dc.disconnect(rsUser);
            dc.disconnect(stmt1);
            dc.disconnect(con);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    search();
}//GEN-LAST:event_jButton1ActionPerformed

private void txt_SearchKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyKeyTyped
//    if (evt.getKeyChar() == evt.VK_ENTER) {
//        Search();
//    }
}//GEN-LAST:event_txt_SearchKeyKeyTyped

private void tb_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_EmployeeMouseClicked
//    if (evt.getClickCount() == 2) {
//        DoEdit();
//    }
}//GEN-LAST:event_tb_EmployeeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_userType1;
    public javax.swing.JTable tb_Employee;
    private javax.swing.JTextField txt_SearchKey;
    // End of variables declaration//GEN-END:variables
}
