/*
 * Home.java
 *
 * Created on November 8, 2009, 3:50 PM
 */

package librarymanagementbook;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import util.CloseableTabComponent;

/**
 *
 * @author  HA
 */
public class Home extends javax.swing.JFrame {

    public static String UserLogon = "";
    /** Creates new form Home */
    public Home() {
        initComponents();
        Login.Unlogin(this);
        this.setTitle("Library Management System");
        toolbar.setFloatable(false);
        toolbar.setAutoscrolls(true);
        
        
        tbpanel.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));

        mn_file.setMnemonic('F');
        mn_MenuAbout.setMnemonic('A');
        mn_manager.setMnemonic('M');
        
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize((ds.width) * 5 / 6, (ds.height * 5) / 6);
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        bt_userManager = new javax.swing.JButton();
        bt_EmployeeManager = new javax.swing.JButton();
        bt_BorrowManagement = new javax.swing.JButton();
        bt_BookManagement = new javax.swing.JButton();
        bt_ChangeInfomation = new javax.swing.JButton();
        bt_Logout = new javax.swing.JButton();
        tbpanel = new javax.swing.JTabbedPane();
        mn_bar = new javax.swing.JMenuBar();
        mn_file = new javax.swing.JMenu();
        mn_Login = new javax.swing.JMenuItem();
        mn_ChangeInfomation = new javax.swing.JMenuItem();
        mn_ChangePassword = new javax.swing.JMenuItem();
        me_ConnectionConfig = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mn_Logout = new javax.swing.JMenuItem();
        mn_Exit = new javax.swing.JMenuItem();
        mn_manager = new javax.swing.JMenu();
        mn_UserManager = new javax.swing.JMenuItem();
        mn_EmployeeManager = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mn_BookManagement = new javax.swing.JMenuItem();
        mn_BorrowManagement = new javax.swing.JMenuItem();
        mn_MenuAbout = new javax.swing.JMenu();
        mn_about = new javax.swing.JMenuItem();
        mn_Help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setRollover(true);

        bt_userManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserManager.png"))); // NOI18N
        bt_userManager.setFocusable(false);
        bt_userManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_userManager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_userManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_userManagerMouseEntered(evt);
            }
        });
        bt_userManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_userManagerActionPerformed(evt);
            }
        });
        toolbar.add(bt_userManager);

        bt_EmployeeManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users_1.png"))); // NOI18N
        bt_EmployeeManager.setFocusable(false);
        bt_EmployeeManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_EmployeeManager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_EmployeeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EmployeeManagerActionPerformed(evt);
            }
        });
        toolbar.add(bt_EmployeeManager);

        bt_BorrowManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quan ly phieu muon .png"))); // NOI18N
        bt_BorrowManagement.setFocusable(false);
        bt_BorrowManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_BorrowManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_BorrowManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BorrowManagementActionPerformed(evt);
            }
        });
        toolbar.add(bt_BorrowManagement);

        bt_BookManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pack.gif"))); // NOI18N
        bt_BookManagement.setFocusable(false);
        bt_BookManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_BookManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_BookManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BookManagementActionPerformed(evt);
            }
        });
        toolbar.add(bt_BookManagement);

        bt_ChangeInfomation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kate.png"))); // NOI18N
        bt_ChangeInfomation.setFocusable(false);
        bt_ChangeInfomation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_ChangeInfomation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_ChangeInfomation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ChangeInfomationActionPerformed(evt);
            }
        });
        toolbar.add(bt_ChangeInfomation);

        bt_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown.png"))); // NOI18N
        bt_Logout.setFocusable(false);
        bt_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LogoutActionPerformed(evt);
            }
        });
        toolbar.add(bt_Logout);

        mn_file.setText("File"); // NOI18N
        mn_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_fileActionPerformed(evt);
            }
        });

        mn_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agt_login.png"))); // NOI18N
        mn_Login.setText("Login"); // NOI18N
        mn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_LoginActionPerformed(evt);
            }
        });
        mn_file.add(mn_Login);

        mn_ChangeInfomation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kate.png"))); // NOI18N
        mn_ChangeInfomation.setText("Change Personal Infomation "); // NOI18N
        mn_ChangeInfomation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ChangeInfomationActionPerformed(evt);
            }
        });
        mn_ChangeInfomation.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                mn_ChangeInfomationAncestorRemoved(evt);
            }
        });
        mn_file.add(mn_ChangeInfomation);

        mn_ChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        mn_ChangePassword.setText("Change Password"); // NOI18N
        mn_ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ChangePasswordActionPerformed(evt);
            }
        });
        mn_file.add(mn_ChangePassword);

        me_ConnectionConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connect.png"))); // NOI18N
        me_ConnectionConfig.setText("Connection Setting"); // NOI18N
        me_ConnectionConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                me_ConnectionConfigActionPerformed(evt);
            }
        });
        mn_file.add(me_ConnectionConfig);
        mn_file.add(jSeparator1);

        mn_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown.png"))); // NOI18N
        mn_Logout.setText("Logout"); // NOI18N
        mn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_LogoutActionPerformed(evt);
            }
        });
        mn_file.add(mn_Logout);

        mn_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        mn_Exit.setText("Exit"); // NOI18N
        mn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ExitActionPerformed(evt);
            }
        });
        mn_file.add(mn_Exit);

        mn_bar.add(mn_file);

        mn_manager.setText("Managers"); // NOI18N
        mn_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_managerActionPerformed(evt);
            }
        });

        mn_UserManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserManager.png"))); // NOI18N
        mn_UserManager.setText("Users Mangement"); // NOI18N
        mn_UserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_UserManagerActionPerformed(evt);
            }
        });
        mn_manager.add(mn_UserManager);

        mn_EmployeeManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users.png"))); // NOI18N
        mn_EmployeeManager.setText("Employee Management"); // NOI18N
        mn_EmployeeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_EmployeeManagerActionPerformed(evt);
            }
        });
        mn_manager.add(mn_EmployeeManager);
        mn_manager.add(jSeparator2);

        mn_BookManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pack.gif"))); // NOI18N
        mn_BookManagement.setText("Book Management"); // NOI18N
        mn_BookManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_BookManagementActionPerformed(evt);
            }
        });
        mn_manager.add(mn_BookManagement);

        mn_BorrowManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quan ly phieu muon .png"))); // NOI18N
        mn_BorrowManagement.setText("Borrow Management"); // NOI18N
        mn_BorrowManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_BorrowManagementActionPerformed(evt);
            }
        });
        mn_manager.add(mn_BorrowManagement);

        mn_bar.add(mn_manager);

        mn_MenuAbout.setText("About"); // NOI18N

        mn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        mn_about.setText("About"); // NOI18N
        mn_MenuAbout.add(mn_about);

        mn_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        mn_Help.setText("Help"); // NOI18N
        mn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_HelpActionPerformed(evt);
            }
        });
        mn_MenuAbout.add(mn_Help);

        mn_bar.add(mn_MenuAbout);

        setJMenuBar(mn_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void me_ConnectionConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_me_ConnectionConfigActionPerformed
// TODO add your handling code here:
    int tabCount = tbpanel.getTabCount();

    for (int i = 0; i < tabCount; i++) {
        if (tbpanel.getTitleAt(i).equals("Connection Config")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Connection Config"));
            return;
        }
    }

    ConnectionConfig cc = new ConnectionConfig(this);
    tbpanel.add("Connection Config", cc);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Connection Config"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Connection Config"));
}//GEN-LAST:event_me_ConnectionConfigActionPerformed

private void mn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ExitActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_mn_ExitActionPerformed

private void mn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_LoginActionPerformed
// TODO add your handling code here:
    Login l = new Login(this);
    l.setVisible(true);
}//GEN-LAST:event_mn_LoginActionPerformed

private void mn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_LogoutActionPerformed
// TODO add your handling code here:
    tbpanel.removeAll();
    Login.Unlogin(this);
    JOptionPane.showMessageDialog(null, "Logout Succesfull!");
    mn_Login.setVisible(true);
}//GEN-LAST:event_mn_LogoutActionPerformed

private void mn_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_fileActionPerformed
// TODO add your handling code here:
   
   
}//GEN-LAST:event_mn_fileActionPerformed

private void mn_ChangeInfomationAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mn_ChangeInfomationAncestorRemoved
// TODO add your handling code here:
  
}//GEN-LAST:event_mn_ChangeInfomationAncestorRemoved

private void mn_ChangeInfomationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ChangeInfomationActionPerformed
// TODO add your handling code here:
      for (int i = 0; i < tbpanel.getTabCount(); i++) {
        if (tbpanel.getTitleAt(i).equals("Change personal information")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Change personal information"));
            return;
        }
    }
    ChangePersonalInformation cpi = new ChangePersonalInformation(UserLogon, this);

    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Change personal information", cpi);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Change personal information"));
    tbpanel.setToolTipTextAt(tabCount, "Change personal information");
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Change personal information"));
}//GEN-LAST:event_mn_ChangeInfomationActionPerformed

private void mn_ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ChangePasswordActionPerformed
// TODO add your handling code here:
    for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Change Password")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Change Password"));
            return;
        }
    }
    ChangePassword cp = new ChangePassword(this);
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Change Password", cp);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Change Password"));
    tbpanel.setToolTipTextAt(tabCount, "Change Password");
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Change Password"));
}//GEN-LAST:event_mn_ChangePasswordActionPerformed

private void bt_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LogoutActionPerformed
// TODO add your handling code here:
    tbpanel.removeAll();
    Login.Unlogin(this);
    JOptionPane.showMessageDialog(null, "Logout Succesfull!");
    mn_Login.setVisible(true);
}//GEN-LAST:event_bt_LogoutActionPerformed

private void bt_ChangeInfomationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ChangeInfomationActionPerformed
// TODO add your handling code here:
      for (int i = 0; i < tbpanel.getTabCount(); i++) {
        if (tbpanel.getTitleAt(i).equals("Change personal information")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Change personal information"));
            return;
        }
    }
    ChangePersonalInformation cpi = new ChangePersonalInformation(UserLogon, this);

    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Change personal information", cpi);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Change personal information"));
    tbpanel.setToolTipTextAt(tabCount, "Change personal information");
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Change personal information"));
}//GEN-LAST:event_bt_ChangeInfomationActionPerformed

private void mn_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_managerActionPerformed
// TODO add your handling code here:
    
//     for (int i = 0; i < tbpanel.getTabCount(); i++) {
//
//        if (tbpanel.getTitleAt(i).equals("User Manager")) {
//            tbpanel.setSelectedIndex(tbpanel.indexOfTab("User Manager"));
//            return;
//        }
//    }
//    UserManagement um = new UserManagement();
//    int tabCount = tbpanel.getTabCount();
//    tbpanel.add("User Manager", um);
//    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "User Manager"));
//    tbpanel.setSelectedIndex(tbpanel.indexOfTab("User Manager"));
}//GEN-LAST:event_mn_managerActionPerformed

private void mn_UserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_UserManagerActionPerformed
// TODO add your handling code here:
    for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("User Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("User Manager"));
            return;
        }
    }
    UserManagement um = new UserManagement();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("User Manager", um);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "User Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("User Manager"));
}//GEN-LAST:event_mn_UserManagerActionPerformed

private void bt_userManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_userManagerActionPerformed
// TODO add your handling code here:
      for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("User Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("User Manager"));
            return;
        }
    }
    UserManagement um = new UserManagement();
    int tabCount = tbpanel.getTabCount();

    tbpanel.add("User Manager", um);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "User Manager"));
    tbpanel.setToolTipTextAt(tabCount, "User Manager");
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("User Manager"));
}//GEN-LAST:event_bt_userManagerActionPerformed

private void mn_EmployeeManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_EmployeeManagerActionPerformed
// TODO add your handling code here:
     for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Employee Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Employee Manager"));
            return;
        }
    }
    EmployManagement um = new EmployManagement();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Employee Manager", um);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Employee Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Employee Manager"));
}//GEN-LAST:event_mn_EmployeeManagerActionPerformed

private void mn_BookManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_BookManagementActionPerformed
// TODO add your handling code here:
     for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Book Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Book Manager"));
            return;
        }
    }
    BookManagement um = new BookManagement();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Book Manager", um);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Book Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Book Manager"));
}//GEN-LAST:event_mn_BookManagementActionPerformed

private void bt_EmployeeManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EmployeeManagerActionPerformed
// TODO add your handling code here:
    for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Employee Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Employee Manager"));
            return;
        }
    }
    EmployManagement um = new EmployManagement();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Employee Manager", um);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Employee Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Employee Manager"));
}//GEN-LAST:event_bt_EmployeeManagerActionPerformed

private void bt_BookManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BookManagementActionPerformed
// TODO add your handling code here:
     for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Book Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Book Manager"));
            return;
        }
    }
    BookManagement um = new BookManagement();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Book Manager", um);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Book Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Book Manager"));
}//GEN-LAST:event_bt_BookManagementActionPerformed

private void mn_BorrowManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_BorrowManagementActionPerformed
// TODO add your handling code here:
    
     for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Borrow Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Borrow Manager"));
            return;
        }
    }
    BorrowManager om = new BorrowManager();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Borrow Manager", om);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Borrow Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Borrow Manager"));
  
}//GEN-LAST:event_mn_BorrowManagementActionPerformed

private void mn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_HelpActionPerformed
// TODO add your handling code here:
    try {
        Runtime.getRuntime().exec("hh.exe " + System.getProperty("user.dir") + "/Help.chm");
    } catch (IOException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_mn_HelpActionPerformed

private void bt_BorrowManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BorrowManagementActionPerformed
// TODO add your handling code here:
     for (int i = 0; i < tbpanel.getTabCount(); i++) {

        if (tbpanel.getTitleAt(i).equals("Borrow Manager")) {
            tbpanel.setSelectedIndex(tbpanel.indexOfTab("Borrow Manager"));
            return;
        }
    }
    BorrowManager om = new BorrowManager();
    int tabCount = tbpanel.getTabCount();
    tbpanel.add("Borrow Manager", om);
    tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(tbpanel, "Borrow Manager"));
    tbpanel.setSelectedIndex(tbpanel.indexOfTab("Borrow Manager"));
}//GEN-LAST:event_bt_BorrowManagementActionPerformed

private void bt_userManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_userManagerMouseEntered

}//GEN-LAST:event_bt_userManagerMouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new 
                
                Runnable() {
            public void run() {
                
                 try {
                    com.jtattoo.plaf.mint.MintLookAndFeel.setTheme("Default", "INSERT YOUR LICENSE KEY HERE", "Library Management System");
                    UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");


                    new Home().setVisible(true);

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_BookManagement;
    private javax.swing.JButton bt_BorrowManagement;
    private javax.swing.JButton bt_ChangeInfomation;
    private javax.swing.JButton bt_EmployeeManager;
    private javax.swing.JButton bt_Logout;
    public javax.swing.JButton bt_userManager;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JMenuItem me_ConnectionConfig;
    private javax.swing.JMenuItem mn_BookManagement;
    private javax.swing.JMenuItem mn_BorrowManagement;
    public javax.swing.JMenuItem mn_ChangeInfomation;
    public javax.swing.JMenuItem mn_ChangePassword;
    private javax.swing.JMenuItem mn_EmployeeManager;
    public javax.swing.JMenuItem mn_Exit;
    private javax.swing.JMenuItem mn_Help;
    public javax.swing.JMenuItem mn_Login;
    public javax.swing.JMenuItem mn_Logout;
    public javax.swing.JMenu mn_MenuAbout;
    public javax.swing.JMenuItem mn_UserManager;
    private javax.swing.JMenuItem mn_about;
    private javax.swing.JMenuBar mn_bar;
    public javax.swing.JMenu mn_file;
    public javax.swing.JMenu mn_manager;
    public javax.swing.JTabbedPane tbpanel;
    public javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

}
