/*
 * ListAllProducts.java
 *
 * Created on April 12, 2009, 9:34 AM
 */
package librarymanagementbook;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.DBConnection;
import util.Search;
import java.sql.*;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class ListAllEmployee extends javax.swing.JFrame {

    DBConnection dc = new DBConnection();
    DefaultTableModel d;
    AddBorrow ao;
    Connection con;
    

    /** Creates new form ListAllProducts */
    public ListAllEmployee() {
        initComponents();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        SetModel();

    }

    /**
     * This constructor is used to initialize a new ListAllProducts form object.
     * @param a - The AddOrder object
     */
    public ListAllEmployee(AddBorrow a) {
        this.ao = a;

        initComponents();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        SetModel();
    }

    /**
     * This constructor is used to initialize a new ListAllUser form object.
     * @param s - The NewSalesBill object
     */
    

    /**
     * This constructor is used to initialize a new ListAllUser form object.
     * @param o - The OrderDetails object
     */
    

    /**
     * This constructor is used to initialize a new ListAllUser form object.
     * @param sd - The SalesBillDetails object
     */
  
    /**This method will Set model for the table
     * 
     */
    public void SetModel() {
        String sql = "select * from Employee";
        dc.executequery(sql);
        d = new DefaultTableModel(dc.data, dc.header) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_Customer.setModel(d);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Customer = new javax.swing.JTable();
        bt_Add = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();
        txt_Employee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Choose Customer");
        setResizable(false);

        tb_Customer.getTableHeader().setReorderingAllowed(false);
        tb_Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_CustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Customer);

        bt_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_add.png"))); // NOI18N
        bt_Add.setText("Add");
        bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddActionPerformed(evt);
            }
        });

        bt_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Name Employee:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(bt_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_Cancel)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txt_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**This method will add add customer to the list
     * 
     */
    public void DoAdd() {
        if (tb_Customer.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Please choose one customer!");
            return;
        }
        int Row[] = tb_Customer.getSelectedRows();
        if (Row.length > 1) {
            JOptionPane.showMessageDialog(null, "You can choose only one customer at same time!");
            return;
        }
        for (int i = 0; i < Row.length; i++) {
            Vector v = (Vector) d.getDataVector().elementAt(Row[i]);
            if (ao != null) {
                ao.txt_CustName.setText(v.elementAt(1).toString());
                this.dispose();
                ao.setVisible(true);

            }
//            if (nsb != null) {
//                nsb.User = v;
//                nsb.txt_customer.setText(v.elementAt(1).toString());
//                nsb.txt_discount.setText(v.elementAt(8).toString());
//                nsb.txt_totalpaid.setText(String.valueOf(nsb.getTotalPaid()));
//                this.dispose();
//            }
//            if (sbd != null) {
//                sbd.lb_name.setText(v.elementAt(1).toString());
//                sbd.txt_discount.setText(v.elementAt(8).toString());
//                sbd.txt_totalpaid.setText(String.valueOf(sbd.getTotalPaid()));
//                this.dispose();
//            }
//            if (od != null) {
//                od.lb_name.setText(v.elementAt(1).toString());
//                this.dispose();
//            }

        }
    }
private void bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddActionPerformed

    DoAdd();

}//GEN-LAST:event_bt_AddActionPerformed

private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
    this.dispose();
}//GEN-LAST:event_bt_CancelActionPerformed

private void tb_CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_CustomerMouseClicked
    if (evt.getClickCount() == 2) {
        DoAdd();
    }
}//GEN-LAST:event_tb_CustomerMouseClicked

public void search() {
        try {
            
            String searchKey = txt_Employee.getText();
            Search s = new Search();
            con = dc.connect();
            Statement stmt1 = con.createStatement();
            String sql = s.getSQLQuery("Employee", searchKey);
            dc.executequery(sql);
            
             d = new DefaultTableModel(dc.data, dc.header) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_Customer.setModel(d);
        if(dc.data.size() == 0){
            JOptionPane.showMessageDialog(this, "Not Search Employee");
        }
        
             
        }catch(Exception e){
        
            e.printStackTrace();
        }
    }

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    search();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListAllEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Customer;
    private javax.swing.JTextField txt_Employee;
    // End of variables declaration//GEN-END:variables
}
