/*
 * Login.java
 *
 * Created on November 8, 2009, 3:50 PM
 */

package librarymanagementbook;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import util.CloseableTabComponent;
import util.DBConnection;
import util.MD5;

/**
 *
 * @author  HA
 */
public class Login extends javax.swing.JFrame {

    String username, password;
    DBConnection dc;
    static Home home;
    
    public static void Unlogin(Home h) {
        h.mn_manager.setVisible(false);
        //h.mn_Tools.setVisible(false);
        h.mn_ChangeInfomation.setVisible(false);
        h.mn_ChangePassword.setVisible(false);
        h.mn_Logout.setVisible(false);
        h.toolbar.setVisible(false);
        h.mn_UserManager.setVisible(false);
        h.bt_userManager.setVisible(false);

    }
 public static void UserloginSucceed() {
        if (home != null) {
            home.mn_Login.setVisible(false);
            home.tbpanel.removeAll();
            home.mn_manager.setVisible(true);
           // home.mn_Tools.setVisible(true);
            home.mn_ChangeInfomation.setVisible(true);
            home.mn_ChangePassword.setVisible(true);
            home.mn_Logout.setVisible(true);
            home.toolbar.setVisible(true);

//            if (home.AdminLogin == true) {
                home.mn_UserManager.setVisible(true);
                home.bt_userManager.setVisible(true);
//            } else {
//                home.mn_UserManager.setVisible(false);
//                home.bt_userManager.setVisible(false);
//            }
        } else {
            Home h = new Home();
            h.setVisible(true);
            h.mn_manager.setVisible(true);
           // h.mn_Tools.setVisible(true);
            h.mn_ChangeInfomation.setVisible(true);
            h.mn_ChangePassword.setVisible(true);
            h.mn_Logout.setVisible(true);
            h.toolbar.setVisible(true);

//            if (h.AdminLogin == true) {
                h.mn_UserManager.setVisible(true);
                h.bt_userManager.setVisible(true);
//            } else {
//                h.mn_UserManager.setVisible(false);
//                h.bt_userManager.setVisible(false);
//            }
        }


    }

 public Login() {
        initComponents();
        dc = new DBConnection(this);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        txt_user.requestFocus();
        txt_user.selectAll();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);

    }

    public Login(Home h) {
        this.home = h;
        initComponents();
        dc = new DBConnection(this,home);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        txt_user.requestFocus();
        txt_user.selectAll();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
    }

       public void doLogin() {
        username = txt_user.getText();
        password = MD5.getHashString(String.valueOf(txt_pass.getPassword()));
       // String sqlAdmin = "select * from tblAdmin where UserName = '" + username + "' and Password = '" + password + "'";
        String sqlUser = "select * from tblUsers where UserName = '" + username + "' and Password = '" + password + "'";
        dc.executequery(sqlUser);


        if (dc.data.isEmpty() == false) {
            //home.AdminLogin = false;
            home.UserLogon = username;
            Login.UserloginSucceed();
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "User : ' " + home.UserLogon + " ' Login Succesfull!");
            this.dispose();
//            home.setVisible(true);

        } else {
//            dc.executequery(sqlAdmin);
//            if (dc.data.isEmpty() == false) {
//               // home.AdminLogin = true;
//                home.UserLogon = username;
//                Login.UserloginSucceed();
//                this.setVisible(false); 
//                JOptionPane.showMessageDialog(null, "Admin: ' " + username + " ' Login Succesfull!");
//                this.dispose();
//                home.setVisible(true);
//
//            } else {
                txt_pass.requestFocus();
                txt_pass.selectAll();
                JOptionPane.showMessageDialog(this, "Invalid user or password..");
//            }
        }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to Library Management Book"); // NOI18N
        setName("fr_Login"); // NOI18N
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font(".VnArial", 0, 24));
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("  Library Management System");

        lb_username.setText("Username"); // NOI18N

        lb_password.setText("Password"); // NOI18N

        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton1.setText("Log in"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        jButton2.setText("Cancel"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connect.png"))); // NOI18N
        jButton3.setText("Connection Config"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_username)
                            .addComponent(lb_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))))
                        .addGap(8, 8, 8)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_username)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_password)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
   doLogin();
   
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    this.dispose();
    Home h = new Home();
    h.setVisible(true);
    int tabCount = h.tbpanel.getTabCount();

    for (int i = 0; i < tabCount; i++) {
        if (h.tbpanel.getTitleAt(i).equals("Connection Config")) {
            h.tbpanel.setSelectedIndex(h.tbpanel.indexOfTab("Connection Config"));
            return;
        }
    }

    ConnectionConfig cc = new ConnectionConfig(h);
    h.tbpanel.add("Connection Config", cc);
    h.tbpanel.setTabComponentAt(tabCount, new CloseableTabComponent(h.tbpanel, "Connection Config"));
    h.tbpanel.setSelectedIndex(h.tbpanel.indexOfTab("Connection Config"));
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
// TODO add your handling code here:
    if (evt.getKeyChar() == evt.VK_ENTER) {
        doLogin();
    }
}//GEN-LAST:event_txt_passKeyTyped

private void txt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyTyped
// TODO add your handling code here:
    if (evt.getKeyChar() == evt.VK_ENTER) {
        doLogin();
    }
}//GEN-LAST:event_txt_userKeyTyped

private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
// TODO add your handling code here:
    if (evt.getKeyChar() == evt.VK_ENTER) {
        doLogin();
    }
}//GEN-LAST:event_jButton1KeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new 
                
                Runnable() {
            public void run() {
               try {
                    com.jtattoo.plaf.mint.MintLookAndFeel.setTheme("Default", "INSERT YOUR LICENSE KEY HERE", "Medical Store Billing");
                    UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");

                    new Login().setVisible(true);

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_username;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

}
