/*
 * UserManagement.java
 *
 * Created on April 6, 2009, 9:38 PM
 */
package librarymanagementbook;

import java.awt.event.ItemEvent;
import java.sql.*;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.CloseableTabComponent;
import util.DBConnection;
import util.Search;

/**
 *
 * @author  Nguyen Manh Truong
 */
public class UserManagement extends javax.swing.JPanel {

    DBConnection dc;
    Connection con;
    Statement stmt1, stmt2;
    ResultSet rs;
    Vector vtcolumn_user, vtdata_user;
    DefaultTableModel user_model = new DefaultTableModel(vtdata_user, vtcolumn_user);
    SimpleDateFormat formatDate;

    /** Creates new form UserManagement */
    public UserManagement() {
        initComponents();

        formatDate = new SimpleDateFormat("dd-MM-yyyy");
        dc = new DBConnection();
        //dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        SetModel();
    }

    /**This method use to set data model for table
     * 
     */
    public void SetModel() {
        try {
            con = dc.connect();
            tb_User.setModel(user_model);
            stmt2 = con.createStatement();
            vtdata_user = new Vector();
            vtcolumn_user = new Vector();

            //Add Header for User Table Model
            vtcolumn_user.add("UserName");
            vtcolumn_user.add("Full Name");
            vtcolumn_user.add("Email");
            vtcolumn_user.add("Birthday");
            vtcolumn_user.add("Gender");
            vtcolumn_user.add("Phone");
            String sqlUser = "select UserName,u_name,Email,BirthDate,Gender,Phone from tblUsers";
            ResultSet rsUser = stmt2.executeQuery(sqlUser);



            while (rsUser.next()) {

                Vector temp = new Vector();

                temp.add(rsUser.getString(1));
                temp.add(rsUser.getString(2));
                temp.add(rsUser.getString(3));
                // temp.add(rsUser.getDate("BirthDate"));

                temp.add(formatDate.format(rsUser.getDate(4)));
                boolean gender = rsUser.getBoolean(5);


                if (gender == true) {
                    temp.add("Male");
                }

                if (gender == false) {
                    temp.add("Female");
                }
                temp.add(rsUser.getString(6));
                vtdata_user.add(temp);
            }


            user_model = new DefaultTableModel(vtdata_user, vtcolumn_user) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tb_User.setModel(user_model);

            dc.disconnect(rsUser);
            dc.disconnect(stmt2);
            dc.disconnect(con);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**This method use to edit user
     * 
     */
    public void DoEdit() {
        
        int Row[] = tb_User.getSelectedRows();
        if (Row.length > 1) {
        JOptionPane.showMessageDialog(null, "You can choose only one user edit at same time!");
        return;
        }
        if (tb_User.getSelectedRow() >= 0) {
            EditUser eu = new EditUser(this);
            eu.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "You have not choose any User to edit");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_User = new javax.swing.JTable();
        bt_edit = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        lb_userType1 = new javax.swing.JLabel();
        txt_SearchKey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List All Users"));

        tb_User.setAutoCreateRowSorter(true);
        tb_User.setModel(user_model);
        tb_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_User);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil_48.png"))); // NOI18N
        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete.png"))); // NOI18N
        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add user.png"))); // NOI18N
        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        lb_userType1.setText("Username");

        txt_SearchKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SearchKeyKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lb_userType1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                        .addComponent(bt_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_delete)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_add)
                        .addComponent(bt_edit)
                        .addComponent(bt_delete)
                        .addComponent(lb_userType1)
                        .addComponent(txt_SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
//
    DoEdit();
}//GEN-LAST:event_bt_editActionPerformed

private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed

    int Row[] = tb_User.getSelectedRows();
    if (Row.length > 1) {
        JOptionPane.showMessageDialog(null, "You can choose only one user delete at same time!");
        return;
    }
    if (tb_User.getSelectedRow() < 0) {
        JOptionPane.showMessageDialog(null, "Please choose user to delete!");
    } else {


        Vector v = new Vector();
        String UserName = null;
        v = (Vector) user_model.getDataVector().elementAt(tb_User.getSelectedRow());
        UserName = v.elementAt(0).toString();
        if (JOptionPane.showConfirmDialog(null, "Are you sure want to delete User : " + UserName, "Library Management System", JOptionPane.OK_CANCEL_OPTION) == 0) {
            String sqlDelUser = "delete from tblUsers where Username = '" + UserName + "'";
            dc.execute(sqlDelUser);

        }



        SetModel();
    }
}//GEN-LAST:event_bt_deleteActionPerformed

private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
    AddUser au = new AddUser(this);
    au.setVisible(true);
}//GEN-LAST:event_bt_addActionPerformed
    /**This method use to seach user
     * 
     */
    public void search() {
        try {
            String searchKey = txt_SearchKey.getText();
            Search s = new Search();
            con = dc.connect();
            stmt1 = con.createStatement();


            String sql = s.getSQLQuery("tblUsers", searchKey);

            vtdata_user = new Vector();
            ResultSet rsUser = stmt1.executeQuery(sql);
            while (rsUser.next()) {

                Vector temp = new Vector();

                temp.add(rsUser.getString("UserName"));
                temp.add(rsUser.getString("U_Name"));
                temp.add(rsUser.getString("Email"));
                // temp.add(rsUser.getDate("BirthDate"));

                temp.add(formatDate.format(rsUser.getDate("BirthDate")));
                boolean gender = rsUser.getBoolean("Gender");


                if (gender == true) {
                    temp.add("Male");
                }

                if (gender == false) {
                    temp.add("Female");
                }
                temp.add(rsUser.getString("Phone"));
                vtdata_user.add(temp);
            }

            user_model = new DefaultTableModel(vtdata_user, vtcolumn_user) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tb_User.setModel(user_model);
            if (vtdata_user.size() == 0) {

                JOptionPane.showMessageDialog(this, "No Search User! ");
            }
            dc.disconnect(rsUser);
            dc.disconnect(stmt1);
            dc.disconnect(con);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    search();
}//GEN-LAST:event_jButton1ActionPerformed

private void txt_SearchKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyKeyTyped
//    if (evt.getKeyChar() == evt.VK_ENTER) {
//        Search();
//    }
}//GEN-LAST:event_txt_SearchKeyKeyTyped

private void tb_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_UserMouseClicked
//    if (evt.getClickCount() == 2) {
//        DoEdit();
//    }
}//GEN-LAST:event_tb_UserMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_userType1;
    public javax.swing.JTable tb_User;
    private javax.swing.JTextField txt_SearchKey;
    // End of variables declaration//GEN-END:variables
}
